DATASET:
  Data_augementation: true
NETWORK:
  Backbone: ResNet50
  INPUT_SIZE: 256
  MARGIN: 1.0
  embedding_size: 128
PROJECT:
  dataset_name: person_classification
  group: Classification_v0
  group_dir: /mnt/Ressources/Andres/runs/Classification_v0
  project: Active_Learning_Datanet
  project_dir: /mnt/Ressources/Andres/runs
TEST:
  batch_size: 16
TRAIN:
  EPOCH_SLIT: 60
  EPOCH_WARMUP: 5
  EPOCH_WHOLE: 60
  MILESTONES:
  - 30
  - 60
  - 90
  batch_size: 32
  lr: 0.002
  test_each: 1
  transfer_weight_path: /mnt/Ressources/Andres/runs/imagenet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
  weight_lossnet_loss: 1.0
  weight_decay: 0.00002
